### ISSUE TITLE
Tests Fail Because They're Expecting a Different Code Pattern

### ISSUE THREAD

**Issue by karen-olson** [learn-co-curriculum/react-hooks-redux-crud-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/4324/assignments/127799?module_item_id=264404

### Concern

I've completed this lab and the app is functioning as described in the Readme, but I still have 2 failing tests. One of the tests is related to code that was pre-written in the repo (Restaurant.js).

I believe the tests are failing because they're expecting a different code pattern than what the ReadMe is instructing you to do. 

For example, the test for the Restaurant component renders the following code: 

    <Provider store={store}>
      <Restaurant restaurant={restaurant2} />
    </Provider>

and then looks to see whether the restaurant is able to be deleted. It throws a TypeError, saying that handleDeleteRestaurant is not a function. 

In the pre-written code, they were passing the action creator function down as a prop from RestaurantsContainer --> Restaurants --> Restaurant. So the Restaurant component, as written in the test file, doesn't have access to the action creator. 

This also happened with the "Delete Review" test in Review.test.js.

**Comment by graciemcguire** [comment]
Hey @karen-olson so so sorry for the delay here, this issue got lost in my Github inbox!
I'm struggling to recreate this issue. The pre-written code you mentioned in `Restaurant.js` appears to be a component that is provided a prop of a `restaurant`, and the renderable code is a couple labels and the button without any actions.
The actions shouldn't need to be passed down however, as any component should be able to access our store if need be when we're using Redux! 😀

I recognize it has been awhile since you initially raised this issue, and you've likely solved it by now so I'm going to close it for now, but if you think I closed it in error please reopen and I'm happy to take another look. 

Thanks again for the feedback, and again my apologies for the delay.
Happy coding!
